import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
for(const file of ['index.html','styles.css','evaluation.css','data.js','level2-extension.js','legal-audit-2026-08.js','hardening.js','level2-version.js','logic.js','store.js','app.js','evaluation.js','evaluation-data.js','exam-blueprint.js'])assert.ok(fs.existsSync(file),`Missing ${file}`);
for(const file of ['app.js','evaluation.js','exam-blueprint.js','store.js'])execFileSync(process.execPath,['--check',file],{stdio:'pipe'});
const html=fs.readFileSync('index.html','utf8');
for(const token of ['app.js?v=2.0.0','evaluation.js?v=2.0.0','0 / 18 dossiers','Mémo professionnel — méthode effective · Niveau 2','Grand livre → décompte'])assert.ok(html.includes(token),`Missing token: ${token}`);
const evalJs=fs.readFileSync('evaluation.js','utf8');
for(const token of ['tva_avance_final_evaluation_v3_blueprint','ATTESTATION DE PARCOURS','Niveau 2','CASES.length','selectBlueprintQuestions','5 blocs de compétences'])assert.ok(evalJs.includes(token),`Missing evaluation token: ${token}`);
const storeJs=fs.readFileSync('store.js','utf8');
assert.match(storeJs,/tva_avance_final_evaluation_v3_blueprint/);
console.log('OK — smoke advanced Level 2 blueprint v3');
