import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
for(const file of ['index.html','styles.css','evaluation.css','data.js','level2-extension.js','legal-audit-2026-08.js','hardening.js','level2-version.js','logic.js','store.js','app.js','evaluation.js','evaluation-data.js','exam-blueprint.js','ux-v3.js','atelier-loader.js','atelier-practice.js','atelier-option-order.js','atelier-practice.css'])assert.ok(fs.existsSync(file),`Missing ${file}`);
for(const file of ['app.js','evaluation.js','exam-blueprint.js','store.js','hardening.js','level2-version.js','ux-v3.js','atelier-loader.js','atelier-practice.js','atelier-option-order.js'])execFileSync(process.execPath,['--check',file],{stdio:'pipe'});
const html=fs.readFileSync('index.html','utf8');
for(const token of ['app.js?v=2.0.0','evaluation.js?v=2.0.0','0 / 18 dossiers','Mémo professionnel — méthode effective · Niveau 2','Réflexe déclaration en 60 secondes','analyser les faits → déclarer → corriger → contrôler'])assert.ok(html.includes(token),`Missing token: ${token}`);
const evalJs=fs.readFileSync('evaluation.js','utf8');
for(const token of ['tva_avance_final_evaluation_v3_blueprint','ATTESTATION DE PARCOURS','Niveau 2','CASES.length','selectBlueprintQuestions','5 blocs de compétences'])assert.ok(evalJs.includes(token),`Missing evaluation token: ${token}`);
const storeJs=fs.readFileSync('store.js','utf8');
assert.match(storeJs,/tva_avance_final_evaluation_v3_blueprint/);
assert.match(storeJs,/atelier-loader\.js/);
assert.match(storeJs,/tva_avance_atelier_review_v1/);
assert.match(storeJs,/tva_avance_atelier_closing_v1/);
const atelier=fs.readFileSync('atelier-practice.js','utf8');
for(const token of ['Corriger un décompte & traiter une concordance','sans audit de dossier','Exercice — Décompte à corriger','Exercice — Rectificatif / concordance','Différence nette en faveur de l’AFC','CHF 1’815.00','REVIEW_SCOPE=\'declaration-review-v2\''])assert.ok(atelier.includes(token),`Missing atelier token: ${token}`);
const ux=fs.readFileSync('ux-v3.js','utf8');
for(const token of ['Niveau 2 · Déclarations avancées','Afficher sources et contrôles','Corrections, valeur & clôture'])assert.ok(ux.includes(token),`Missing UX token: ${token}`);
const version=fs.readFileSync('level2-version.js','utf8');
assert.match(version,/VERSION='2\.3\.1'/);
const hardening=fs.readFileSync('hardening.js','utf8');
assert.match(hardening,/PARCOURS_VERSION='2\.3\.1'/);
assert.ok(!hardening.includes("PARCOURS_VERSION='1.1.0'"),'Legacy hardening version returned');
console.log('OK — smoke advanced Level 2 declaration trainer v2.3.1');
